<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

/**
 * Protobuf type <code>common.Modulation</code>
 */
class Modulation
{
    /**
     * LoRa
     *
     * Generated from protobuf enum <code>LORA = 0;</code>
     */
    const LORA = 0;
    /**
     * FSK
     *
     * Generated from protobuf enum <code>FSK = 1;</code>
     */
    const FSK = 1;
}

