<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

/**
 * Protobuf type <code>common.MType</code>
 */
class MType
{
    /**
     * JoinRequest.
     *
     * Generated from protobuf enum <code>JoinRequest = 0;</code>
     */
    const JoinRequest = 0;
    /**
     * JoinAccept.
     *
     * Generated from protobuf enum <code>JoinAccept = 1;</code>
     */
    const JoinAccept = 1;
    /**
     * UnconfirmedDataUp.
     *
     * Generated from protobuf enum <code>UnconfirmedDataUp = 2;</code>
     */
    const UnconfirmedDataUp = 2;
    /**
     * UnconfirmedDataDown.
     *
     * Generated from protobuf enum <code>UnconfirmedDataDown = 3;</code>
     */
    const UnconfirmedDataDown = 3;
    /**
     * ConfirmedDataUp.
     *
     * Generated from protobuf enum <code>ConfirmedDataUp = 4;</code>
     */
    const ConfirmedDataUp = 4;
    /**
     * ConfirmedDataDown.
     *
     * Generated from protobuf enum <code>ConfirmedDataDown = 5;</code>
     */
    const ConfirmedDataDown = 5;
    /**
     * RejoinRequest.
     *
     * Generated from protobuf enum <code>RejoinRequest = 6;</code>
     */
    const RejoinRequest = 6;
    /**
     * Proprietary.
     *
     * Generated from protobuf enum <code>Proprietary = 7;</code>
     */
    const Proprietary = 7;
}

