<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

/**
 * Protobuf type <code>common.Region</code>
 */
class Region
{
    /**
     * EU868
     *
     * Generated from protobuf enum <code>EU868 = 0;</code>
     */
    const EU868 = 0;
    /**
     * US915
     *
     * Generated from protobuf enum <code>US915 = 2;</code>
     */
    const US915 = 2;
    /**
     * CN779
     *
     * Generated from protobuf enum <code>CN779 = 3;</code>
     */
    const CN779 = 3;
    /**
     * EU433
     *
     * Generated from protobuf enum <code>EU433 = 4;</code>
     */
    const EU433 = 4;
    /**
     * AU915
     *
     * Generated from protobuf enum <code>AU915 = 5;</code>
     */
    const AU915 = 5;
    /**
     * CN470
     *
     * Generated from protobuf enum <code>CN470 = 6;</code>
     */
    const CN470 = 6;
    /**
     * AS923
     *
     * Generated from protobuf enum <code>AS923 = 7;</code>
     */
    const AS923 = 7;
    /**
     * AS923 with -1.80 MHz frequency offset
     *
     * Generated from protobuf enum <code>AS923_2 = 12;</code>
     */
    const AS923_2 = 12;
    /**
     * AS923 with -6.60 MHz frequency offset
     *
     * Generated from protobuf enum <code>AS923_3 = 13;</code>
     */
    const AS923_3 = 13;
    /**
     * KR920
     *
     * Generated from protobuf enum <code>KR920 = 8;</code>
     */
    const KR920 = 8;
    /**
     * IN865
     *
     * Generated from protobuf enum <code>IN865 = 9;</code>
     */
    const IN865 = 9;
    /**
     * RU864
     *
     * Generated from protobuf enum <code>RU864 = 10;</code>
     */
    const RU864 = 10;
    /**
     * ISM2400 (LoRaWAN 2.4 GHz)
     *
     * Generated from protobuf enum <code>ISM2400 = 11;</code>
     */
    const ISM2400 = 11;
}

