<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_session.proto

namespace Storage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>storage.DeviceGatewayRXInfoPB</code>
 */
class DeviceGatewayRXInfoPB extends \Google\Protobuf\Internal\Message
{
    /**
     * Gateway ID.
     *
     * Generated from protobuf field <code>bytes gateway_id = 1;</code>
     */
    private $gateway_id = '';
    /**
     * RSSI.
     *
     * Generated from protobuf field <code>int32 rssi = 2;</code>
     */
    private $rssi = 0;
    /**
     * LoRa SNR.
     *
     * Generated from protobuf field <code>double lora_snr = 3;</code>
     */
    private $lora_snr = 0.0;
    /**
     * Board.
     *
     * Generated from protobuf field <code>uint32 board = 4;</code>
     */
    private $board = 0;
    /**
     * Antenna.
     *
     * Generated from protobuf field <code>uint32 antenna = 5;</code>
     */
    private $antenna = 0;
    /**
     * Gateway specific context.
     *
     * Generated from protobuf field <code>bytes context = 6;</code>
     */
    private $context = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gateway_id
     *           Gateway ID.
     *     @type int $rssi
     *           RSSI.
     *     @type float $lora_snr
     *           LoRa SNR.
     *     @type int $board
     *           Board.
     *     @type int $antenna
     *           Antenna.
     *     @type string $context
     *           Gateway specific context.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DeviceSession::initOnce();
        parent::__construct($data);
    }

    /**
     * Gateway ID.
     *
     * Generated from protobuf field <code>bytes gateway_id = 1;</code>
     * @return string
     */
    public function getGatewayId()
    {
        return $this->gateway_id;
    }

    /**
     * Gateway ID.
     *
     * Generated from protobuf field <code>bytes gateway_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGatewayId($var)
    {
        GPBUtil::checkString($var, False);
        $this->gateway_id = $var;

        return $this;
    }

    /**
     * RSSI.
     *
     * Generated from protobuf field <code>int32 rssi = 2;</code>
     * @return int
     */
    public function getRssi()
    {
        return $this->rssi;
    }

    /**
     * RSSI.
     *
     * Generated from protobuf field <code>int32 rssi = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRssi($var)
    {
        GPBUtil::checkInt32($var);
        $this->rssi = $var;

        return $this;
    }

    /**
     * LoRa SNR.
     *
     * Generated from protobuf field <code>double lora_snr = 3;</code>
     * @return float
     */
    public function getLoraSnr()
    {
        return $this->lora_snr;
    }

    /**
     * LoRa SNR.
     *
     * Generated from protobuf field <code>double lora_snr = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLoraSnr($var)
    {
        GPBUtil::checkDouble($var);
        $this->lora_snr = $var;

        return $this;
    }

    /**
     * Board.
     *
     * Generated from protobuf field <code>uint32 board = 4;</code>
     * @return int
     */
    public function getBoard()
    {
        return $this->board;
    }

    /**
     * Board.
     *
     * Generated from protobuf field <code>uint32 board = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBoard($var)
    {
        GPBUtil::checkUint32($var);
        $this->board = $var;

        return $this;
    }

    /**
     * Antenna.
     *
     * Generated from protobuf field <code>uint32 antenna = 5;</code>
     * @return int
     */
    public function getAntenna()
    {
        return $this->antenna;
    }

    /**
     * Antenna.
     *
     * Generated from protobuf field <code>uint32 antenna = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAntenna($var)
    {
        GPBUtil::checkUint32($var);
        $this->antenna = $var;

        return $this;
    }

    /**
     * Gateway specific context.
     *
     * Generated from protobuf field <code>bytes context = 6;</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Gateway specific context.
     *
     * Generated from protobuf field <code>bytes context = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;

        return $this;
    }

}

