<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_session.proto

namespace Storage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>storage.DeviceSessionPBChannel</code>
 */
class DeviceSessionPBChannel extends \Google\Protobuf\Internal\Message
{
    /**
     * Frequency (Hz).
     *
     * Generated from protobuf field <code>uint32 frequency = 1;</code>
     */
    private $frequency = 0;
    /**
     * Min. data-rate.
     *
     * Generated from protobuf field <code>uint32 min_dr = 2;</code>
     */
    private $min_dr = 0;
    /**
     * Max. data-rate.
     *
     * Generated from protobuf field <code>uint32 max_dr = 3;</code>
     */
    private $max_dr = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $frequency
     *           Frequency (Hz).
     *     @type int $min_dr
     *           Min. data-rate.
     *     @type int $max_dr
     *           Max. data-rate.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DeviceSession::initOnce();
        parent::__construct($data);
    }

    /**
     * Frequency (Hz).
     *
     * Generated from protobuf field <code>uint32 frequency = 1;</code>
     * @return int
     */
    public function getFrequency()
    {
        return $this->frequency;
    }

    /**
     * Frequency (Hz).
     *
     * Generated from protobuf field <code>uint32 frequency = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFrequency($var)
    {
        GPBUtil::checkUint32($var);
        $this->frequency = $var;

        return $this;
    }

    /**
     * Min. data-rate.
     *
     * Generated from protobuf field <code>uint32 min_dr = 2;</code>
     * @return int
     */
    public function getMinDr()
    {
        return $this->min_dr;
    }

    /**
     * Min. data-rate.
     *
     * Generated from protobuf field <code>uint32 min_dr = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMinDr($var)
    {
        GPBUtil::checkUint32($var);
        $this->min_dr = $var;

        return $this;
    }

    /**
     * Max. data-rate.
     *
     * Generated from protobuf field <code>uint32 max_dr = 3;</code>
     * @return int
     */
    public function getMaxDr()
    {
        return $this->max_dr;
    }

    /**
     * Max. data-rate.
     *
     * Generated from protobuf field <code>uint32 max_dr = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxDr($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_dr = $var;

        return $this;
    }

}

