<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_session.proto

namespace Storage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>storage.DeviceSessionPBUplinkADRHistory</code>
 */
class DeviceSessionPBUplinkADRHistory extends \Google\Protobuf\Internal\Message
{
    /**
     * Uplink frame-counter.
     *
     * Generated from protobuf field <code>uint32 f_cnt = 1;</code>
     */
    private $f_cnt = 0;
    /**
     * Max SNR (of deduplicated frames received by one or multiple gateways).
     *
     * Generated from protobuf field <code>float max_snr = 2;</code>
     */
    private $max_snr = 0.0;
    /**
     * TX Power (as known by the network-server).
     *
     * Generated from protobuf field <code>uint32 tx_power_index = 3;</code>
     */
    private $tx_power_index = 0;
    /**
     * Number of receiving gateways.
     *
     * Generated from protobuf field <code>uint32 gateway_count = 4;</code>
     */
    private $gateway_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $f_cnt
     *           Uplink frame-counter.
     *     @type float $max_snr
     *           Max SNR (of deduplicated frames received by one or multiple gateways).
     *     @type int $tx_power_index
     *           TX Power (as known by the network-server).
     *     @type int $gateway_count
     *           Number of receiving gateways.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DeviceSession::initOnce();
        parent::__construct($data);
    }

    /**
     * Uplink frame-counter.
     *
     * Generated from protobuf field <code>uint32 f_cnt = 1;</code>
     * @return int
     */
    public function getFCnt()
    {
        return $this->f_cnt;
    }

    /**
     * Uplink frame-counter.
     *
     * Generated from protobuf field <code>uint32 f_cnt = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->f_cnt = $var;

        return $this;
    }

    /**
     * Max SNR (of deduplicated frames received by one or multiple gateways).
     *
     * Generated from protobuf field <code>float max_snr = 2;</code>
     * @return float
     */
    public function getMaxSnr()
    {
        return $this->max_snr;
    }

    /**
     * Max SNR (of deduplicated frames received by one or multiple gateways).
     *
     * Generated from protobuf field <code>float max_snr = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxSnr($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_snr = $var;

        return $this;
    }

    /**
     * TX Power (as known by the network-server).
     *
     * Generated from protobuf field <code>uint32 tx_power_index = 3;</code>
     * @return int
     */
    public function getTxPowerIndex()
    {
        return $this->tx_power_index;
    }

    /**
     * TX Power (as known by the network-server).
     *
     * Generated from protobuf field <code>uint32 tx_power_index = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTxPowerIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->tx_power_index = $var;

        return $this;
    }

    /**
     * Number of receiving gateways.
     *
     * Generated from protobuf field <code>uint32 gateway_count = 4;</code>
     * @return int
     */
    public function getGatewayCount()
    {
        return $this->gateway_count;
    }

    /**
     * Number of receiving gateways.
     *
     * Generated from protobuf field <code>uint32 gateway_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGatewayCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->gateway_count = $var;

        return $this;
    }

}

